### ISSUE TITLE
Is there PHP SDK available?

### ISSUE THREAD

**Issue by reachmefredrick** [box/sdks#2]
I would like to integrate our Box with my PHP application. Is this possible?

Can you please guide me in this?

**Comment by reachmefredrick** [comment]
If there is an option to access using CURL do guide me on that.

**Comment by carycheng** [comment]
Hey @reachmefredrick,

Although we do not have a PHP SDK, our API can be accessed vis CURL. For a guide on how to please refer to [here](https://developer.box.com/reference/). You can click on any of the links to continue.

Please let us know if you run into any other issues!

**Comment by coderintherye** [comment]
@carycheng Would be great if Box could invest in a PHP SDK. Would be a good project for a Box SE for Good Workshop (if those are still a thing)!

**Comment by coderintherye** [comment]
@carycheng Especially considering the docs you linked to don't show a server-based method for leveraging the API (rather only shows the client-side implementation) and that further the Postman example is broken.

**Comment by cbetta** [comment]
@coderintherye all our API reference code samples are server-side code samples. Could you let us know what Postman example is broken?

**Comment by coderintherye** [comment]
@cbetta I think that may not be the case, take for example: https://developer.box.com/reference/post-oauth2-token/ 
The curl code example at the bottom of the "Request Access Token" endpoints defaults to passing a code=[CODE] reference, even though code is a client-side auth code, as noted directly above: "The client-side authorization code passed to your application by Box in the browser redirect after the user has successfully granted your application permission to make API calls on their behalf."

One can remove the optional parameter, but the code sample is not defaulting to the server-side sample.

For Postman, try walking through the example (which by the way, fails to note ahead of time you have to enable 2FA in order to generate the client id and secret to attempt to use). Following the examples results in either a "error_oauth_server_exception" of "There seems to be a problem with this app."

**Comment by cbetta** [comment]
@coderintherye I stand corrected, this is the one and only endpoint that is a frontend endpoint and therefore the curl sample is frontend related. It's related to the OAuth 2.0 flow. This is actually not an API as such, it's simply the OAuth 2.0 authentication URL. It's listed here mostly for posterity. All our other samples are SDK samples for backend usage. 

As for the Postman walkthrough, I recently rewrote the Quick Start Guide and it indeed doesn't mention 2FA as you are prompted to set this up as you go through the guide, I'll make a note to give this a warning upfront. 

It's interesting you get a `error_oauth_server_exception` error. At which state do you get this? When you make a call in Postman or earlier?

**Comment by coderintherye** [comment]
@cbetta When making a call in Postman. Making a call with a different endpoint results in a:
    "error_description": "The client credentials are invalid"
The client credentials are definitely valid, so I assume this is due to the Bearer token being invalid, and so probably what the Postman example needs is a way to ensure all the pre-steps for client credentials are set up correctly. Unless it just assumed we'll just use a temporary developer access token (but if that's the case, well then it would be failing to provide much help at all in setting up the actual flow)

**Comment by cbetta** [comment]
Ah I see the confusion. Just for your information, the Postman collection doesn't have a magical way to know who you are authenticated as. You could indeed use the developer token, but I highly recomment using our Quick Start Guide instead: https://developer.box.com/guides/tooling/postman/quick-start/

I recommend looking at the video, it shows how to set up your own Box App and authenticate through OAuth 2.0 with Postman.

**Comment by coderintherye** [comment]
@cbetta Right, I didn't say it had a magical way. I walked through the quick start steps, that was how I went about setting up Postman with Box, and still arrived at the authentication error. Have you walked through the quick start yourself and had success?

**Comment by cbetta** [comment]
Yes, I wrote the quick start guide which is why I'm so interested to know where this is going wrong. I've gone through the quick start a few hundred times.  If we can figure this out then we can fix it for you. 

Can you confirm for me that your Postman environment has been populated with your Access and Refresh token? And that you have this environment selected?

**Comment by jcleblanc** [comment]
@reachmefredrick in addition to the APIs referenced already, there are two community PHP SDK projects that might be a good starting point, listed [here](https://developer.box.com/support/community-projects/). They are:

- https://github.com/maengkom/boxapi
- https://github.com/golchha21/BoxPHPAPI

I can't speak to their level of integration with the APIs or functionality, since they are managed by the community, but they would at least be a good place to start.

**Comment by coderintherye** [comment]
@cbetta Ok, I walked through it again from scratch and was successful this time. I believe that I skipped this step previously: "To select the Box Postman environment, select Box from the dropdown in the top-right of Postman." 

@jcleblanc Having tried both of those, I'd recommend the latter, as the former is fairly complicated to setup, and complicated by the fact that it has to do two different things for Standard vs. Enterprise users making the config messy. It's also Laravel specific. I'm glad the author created it, but by trying to do both of those things in different classes in the same package it makes for a difficult first-time user experience. Which, really, is why I'm just +1 for Box creating an official PHP SDK. It'd make the on-boarding experience for PHP codebases quite a bit nicer.

**Comment by cbetta** [comment]
Excellent. That's amazing. Good to know it does work.

**Comment by coderintherye** [comment]
@cbetta Why are you wontfix'ing this? 

You guys are that opposed to adding a PHP SDK? 

That attitude is very different than the attitude I experienced working with Box engineers at Box SE for Good. Very disheartening, especially considering all the other official SDK's that have been added.

**Comment by cbetta** [comment]
@coderintherye I totally understand your concerns but we are currently not planning support for a PHP SDK. Leaving this issue open would be sending an incorrect expectation that we are planning to, which I was trying to prevent. 

I highly recommend using pulse.box.com for these kind of large product requests. It's our official direct line to the product teams do request new features including new SDKs.

Have a good weekend!

**Comment by coderintherye** [comment]
@cbetta Interesting, ok, that's definitely a change from the Box I know. The whole reason I chose to keep going with Box is traditionally you all have been developer friendly, especially to social good orgs. Seems that is no longer the case.

**Comment by cbetta** [comment]
@coderintherye I'm sorry to hear that you believe that, I hope you understand we have over 180 API endpoints, 4 official tier 1 SDKs, an OpenApi spec, multiple frontend libraries and a mobile SDK for Android and iOS. I'd find it hard call that unfriendly to developers. 

We have multiple community driven PHP SDKs but we currently have no intend to release our own PHP SDK as any new SDK would need to be supported at the same tier 1 level as our other SDKs which is a considerable development effort. 

That said though, all our APIs can be used in PHP without much complexity and we're always happy to device the right code samples for you if you were to run into any issues. 

Additionally, we're always listening to our customers via Box Pulse. I'd highly recommend you bring your request for a PHP SDK to that forum as it's an absolute direct line to our customers.
